export const SEARCH_REPOSITORIES_START = 'SEARCH_REPOSITORIES_START'
export const SEARCH_REPOSITORIES_SUCCESS = 'SEARCH_REPOSITORIES_SUCCESS'
export const SEARCH_REPOSITORIES_FAILED = 'SEARCH_REPOSITORIES_FAILED'

export const PAGINATION_REPOSITORIES_SUCCESS = 'PAGINATION_REPOSITORIES_SUCCESS'

export const UPDATE_REPOSITORY_SUCCESS = 'UPDATE_REPOSITORY_SUCCESS'
